### ISSUE TITLE
Support for Content Lock (anti-concurrent editing) module 

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/save_edit#1]
Carrying over this issue from the Drupal 7 queue:
https://www.drupal.org/project/save_edit/issues/2358523

> Hello
> Here is a patch that preserves the [content_lock](https://www.drupal.org/project/content_lock) token query string parameter between form posts in order to support content_lock module.
> 
> Without the patch, content_lock refuses to create a lock, so that can prevent a CSRF attack. As a result user is been asked to manually lock the node.
> 
> By the way, I am not sure if save_edit should preserve all Request variables and not only the “destination”

Content Lock has been recently released by @robertgarrigos at https://github.com/backdrop-contrib/content_lock

I will prepare a pull request using the latest patch from that issue for testing: https://www.drupal.org/files/issues/save_edit-support_for_content_lock-2358523-10.patch

**Comment by yorkshire-pudding** [comment]
If anyone uses the Content Lock module, please test the PR.  I will try and test at some point, but don't have time at present.

**Comment by robertgarrigos** [comment]
I can confirm that this PR solves the problem.
